graph_indir: /tigress/jdezoort/IN_samples_samples
model_outdir: /tigress/jdezoort/IN_output/trained_models
plot_outdir: /tigress/jdezoort/IN_output/plots
verbose: 1
n_epoch: 400
batch_size: 1
n_recur: 3
prep: 'LP'
pt_cut: '2'
save_every_n_epoch: 20
save_last_n_epoch: 50
phi_reflect: false
tag: 'LR03_recurrent3_nophi'